### ISSUE TITLE
Enable aggregation of nodes in table

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#16]
The table should accurately display an aggregation set by the graph. 

In a first iteration, we will use the following visual encodings for quantitative and categorical data: 

 * Dot plots with jitter in y direction to encode all the elements in the aggregation, a vertical line at the median value. On hover over a dot we want to display the exact value of the entry and highlight the corresponding person in all other columns. 
 * In line with the categorical vis introduced in #10, aggregated categories will be displayed as a bar chart that is filled horizontally, proportional to the number of people that are in this category. On hover, a tool tip will show the number of the persons in that category and will highlight the people in all other columns of the table.

**Comment by anniecherk** [comment]
Just wanted to confirm 2 things:

1) The dot plot jitter should be in y direction? Because the table is to the right of the tree & hence the data is in rows, there's a lot more horizontal real estate than vertical:
![h vs v_1](https://cloud.githubusercontent.com/assets/4534857/23152882/5b29fa24-f7c2-11e6-85ae-f4f0ef469f8c.jpg)

I think (a) is easier to read than (b) (ie, jitter horizontally, not vertically). Thoughts?

2) Non-aggregated data is also displayed as a dot plot

**Comment by anniecherk** [comment]
Thoughts on how to handle missing entries (ie, a data point does not have a value for a given column).

Proposed encoding for missing categorical entries: outline where the box would be in a light grey stroke.

![new doc 2017-02-21 11 17 28_3](https://cloud.githubusercontent.com/assets/4534857/23179487/4ef2f7d8-f82b-11e6-9389-19b53d2a3e42.jpg)

Proposed encoding for missing quantitative entries: empty jitter plot with only the median value marked:


![new doc 2017-02-21 11 17 28_4](https://cloud.githubusercontent.com/assets/4534857/23179480/470c3eb2-f82b-11e6-9173-3254b5c60ca1.jpg)

**Comment by alexsb** [comment]
Update: 
Categorical values will be represented as a partially filled square, the fill-height is proportional to the number of cases in that category. 

Text will be represented either as an ellipsis with details on hover, or sorted by frequency. and truncated.
