### ISSUE TITLE
Positioning of nodes off, visible for duplicates

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#212]
Family 27251 in the anon dataset contains the following case: 

![image](https://user-images.githubusercontent.com/2039375/33243664-eb18d9dc-d2a7-11e7-8119-5a70cce24e64.png)

The duplicated women is placed at different positions. That's a problem.

**Comment by cnobre** [comment]
This is happening because in 'hide and aggregate mode', the female nodes are aligned with the position of  their husbands. Because one of the duplicates is in the child role, it never got shifted. Will adjust the x positioning for duplicates to always preserve their original x values and instead align the husband to their position.

**Comment by cnobre** [comment]
<img width="93" alt="screen shot 2017-11-27 at 10 19 56 pm" src="https://user-images.githubusercontent.com/4120607/33303624-781d0398-d3c1-11e7-92d9-2657c96d6509.png">

**Comment by cnobre** [comment]
*Edit. I was wrong! Turns out I was already aligning with the right node. it was a bug in the fact that [node,node.spouse] is not the same as [node].concat(node.spouse). That change fixed the alignment since all spouses are always aligned with the affected one.
