### ISSUE TITLE
Incorrect spouse aggregation

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#71]
![image](https://cloud.githubusercontent.com/assets/2039375/23474340/b7052d5a-fe70-11e6-9020-7394d3b3a91c.png)

**Comment by cnobre** [comment]
I figured out the bug here. The question is, do we want the behavior of clicking on a spouse (say 77 in this case) to also collapse/uncollapse their spouse, even if the spouse is technically below them in the tree? (assuming that people are clicking on couples, not individual people) Or should the collapse operation on 77 only affect itself and the nodes that are strictly above it? 

![screen shot 2017-03-01 at 5 15 24 pm](https://cloud.githubusercontent.com/assets/4120607/23487367/cbd1a2ae-fea2-11e6-88f3-7ab5dd47c95c.png)
