### ISSUE TITLE
Add axis to numerical table columns

### ISSUE THREAD

**Issue by alexsb** [Caleydo/lineage#9]
For numerical values, add a permanently visible axis, like this one (but on top): 

![image](https://cloud.githubusercontent.com/assets/2039375/22801857/c1f0a438-eecb-11e6-9b55-ab5850c8e8ce.png)

**Comment by anniecherk** [comment]
Implementation sketch:
- Add the axis below label
- Only display axis if there is "enough" room: otherwise with many attributes this becomes illegible 
- Label low / mid / high points
![image](https://cloud.githubusercontent.com/assets/4534857/23108484/359ceba6-f6cb-11e6-9129-2a1f365e1225.png)

Issues: 
- making sure the edge values are legible if the neighboring column also has a labeled axis
- allow the user to specify a "reference value" in the panel and either:
        a) display it normally along with the other values
        b) display it instead of the mid value
        c) display it in bold along with the other values

**Comment by alexsb** [comment]
Looks good.

The reference value could also be specified in the panel, but it could also be in both. 
Re labeling - yes, there needs to be enough spacing.

**Comment by alexsb** [comment]
Implemented!
